# Trojan代理客户端配置文件
trojan:
  # 服务器地址 - 请修改为您的实际服务器地址
  server: "your.trojan.server.com"
  # 服务器端口 - 请修改为您的实际端口
  port: 443
  # 密码 - 请修改为您的实际密码
  password: "your_password_here"
  # 是否验证SSL证书
  verify_ssl: false
  # SNI (Server Name Indication) - 通常与服务器地址相同
  sni: "your.trojan.server.com"

# 本地SOCKS5代理设置
local:
  # 监听地址
  listen: "127.0.0.1"
  # 监听端口
  port: 1080

# 日志设置
log:
  # 日志级别: DEBUG, INFO, WARNING, ERROR
  level: "INFO"
  # 日志文件路径 (为空则只输出到控制台)
  file: ""
  # 是否显示详细的请求/响应日志
  verbose_traffic: true
  # 是否显示HTTP请求详情
  show_http_details: true

# 路由规则
routing:
  # 直连域名列表
  direct_domains:
    - "localhost"
    - "127.0.0.1"
    - "*.local"
  
  # 代理域名列表  
  proxy_domains:
    - "*" 